// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZRYA7o5PO0fa_RsQ7rEvAqA-gvkS-hw',
    appId: '1:341089533025:web:79acfc8df2596ec66ffe20',
    messagingSenderId: '341089533025',
    projectId: 'fir-2-bd183',
    authDomain: 'fir-2-bd183.firebaseapp.com',
    storageBucket: 'fir-2-bd183.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV4BpeADBciP0SZCucIqPuHTiVuPzd2TY',
    appId: '1:341089533025:android:42bb2895b9fb06b56ffe20',
    messagingSenderId: '341089533025',
    projectId: 'fir-2-bd183',
    storageBucket: 'fir-2-bd183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPD-4Sg5uML-t6hq3nIeE5Gx_55LuGa1c',
    appId: '1:341089533025:ios:0f024f31b6dd2f6f6ffe20',
    messagingSenderId: '341089533025',
    projectId: 'fir-2-bd183',
    storageBucket: 'fir-2-bd183.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPD-4Sg5uML-t6hq3nIeE5Gx_55LuGa1c',
    appId: '1:341089533025:ios:0f024f31b6dd2f6f6ffe20',
    messagingSenderId: '341089533025',
    projectId: 'fir-2-bd183',
    storageBucket: 'fir-2-bd183.appspot.com',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuZRYA7o5PO0fa_RsQ7rEvAqA-gvkS-hw',
    appId: '1:341089533025:web:9a1a2ae5c20cc0aa6ffe20',
    messagingSenderId: '341089533025',
    projectId: 'fir-2-bd183',
    authDomain: 'fir-2-bd183.firebaseapp.com',
    storageBucket: 'fir-2-bd183.appspot.com',
  );
}
